dist: xenial
sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: stable
  sonarcloud:
    organization: 'narshe1412-github' # the key of the org you chose at step #3
    # token:
    #   secure: SONAR_TOKEN # encrypted value of your token

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  # - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run cibuild
  - sonar-scanner
  - ng deploy --repo=https://github.com/Narshe1412/Code-Institute-Interactive-Frontend-Algorithms --name="Narshe1412" --email=manuel1412@gmail.com --base-href=/Code-Institute-Interactive-Frontend-Algorithms/
